=== Francisco1915/Processamento-Estruturado-de-Informa-o/xmlxsd/reservaTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.visitaOpaiNatal.pt/reservaTypes" targetNamespace="http://www.visitaOpaiNatal.pt/reservaTypes" xmlns:c="http://www.visitaOpaiNatal.pt/commonTypes" elementFormDefault="qualified">

    <xs:import schemaLocation="commonTypes.xsd" namespace="http://www.visitaOpaiNatal.pt/commonTypes"></xs:import>

    <xs:element name="reserva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="familia">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="origem">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="país" type="c:paísType"></xs:element>
                                        <xs:element name="cidade" type="c:cidadeType"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="numElementos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[1-7]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="elementos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elemento" minOccurs="1" maxOccurs="7">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="genero" type="c:generoType"></xs:element>
                                                    <xs:element name="primeiroNome" type="xs:string"></xs:element>
                                                    <xs:element name="segundoNome" type="xs:string"></xs:element>
                                                    <xs:element name="dataNascimento" type="xs:date"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="preferencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dataPrevista" type="c:dataPrioType" minOccurs="1" maxOccurs="5"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Francisco1915/Processamento-Estruturado-de-Informa-o/xmlxsd/ExemplosReservas/reserva3.xml
<?xml version="1.0" encoding="UTF-8"?>
<reserva xmlns="http://www.visitaOpaiNatal.pt/reservaTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.visitaOpaiNatal.pt/reservaTypes reservaTypes.xsd">
    <familia>
        <origem>
            <país>United Kingdom</país>
            <cidade>London</cidade>
        </origem>
        <numElementos>4</numElementos>
        <elementos>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Pedro</primeiroNome>
                <segundoNome>Moreira</segundoNome>
                <dataNascimento>1999-03-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Marta</primeiroNome>
                <segundoNome>Silva</segundoNome>
                <dataNascimento>2008-10-25</dataNascimento>
            </elemento>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Marco</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2020-08-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Sonia</primeiroNome>
                <segundoNome>Moreira</segundoNome>
                <dataNascimento>2020-08-14</dataNascimento>
            </elemento>
        </elementos>
    </familia>
    <preferencias>
        <dataPrevista prioridade="1">2022-12-22</dataPrevista>
        <dataPrevista prioridade="2">2022-12-21</dataPrevista>
        <dataPrevista prioridade="3">2022-12-18</dataPrevista>
    </preferencias>
</reserva>

=== Francisco1915/Processamento-Estruturado-de-Informa-o/xmlxsd/ExemplosReservas/reserva1.xml
<?xml version="1.0" encoding="UTF-8"?>
<reserva xmlns="http://www.visitaOpaiNatal.pt/reservaTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.visitaOpaiNatal.pt/reservaTypes reservaTypes.xsd">
    <familia>
        <origem>
            <país>United States of America</país>
            <cidade>New York</cidade>
        </origem>
        <numElementos>4</numElementos>
        <elementos>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Francisco</primeiroNome>
                <segundoNome>Pinto</segundoNome>
                <dataNascimento>1962-03-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Luísa</primeiroNome>
                <segundoNome>Borges</segundoNome>
                <dataNascimento>1962-10-25</dataNascimento>
            </elemento>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Luis</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2002-08-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Francisco</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2002-08-14</dataNascimento>
            </elemento>
        </elementos>
    </familia>
    <preferencias>
        <dataPrevista prioridade="1">2022-12-21</dataPrevista>
        <dataPrevista prioridade="2">2022-12-19</dataPrevista>
        <dataPrevista prioridade="3">2022-12-17</dataPrevista>
    </preferencias>
</reserva>

=== Francisco1915/Processamento-Estruturado-de-Informa-o/xmlxsd/reserva.xml
<?xml version="1.0" encoding="UTF-8"?>
<reserva xmlns="http://www.visitaOpaiNatal.pt/reservaTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.visitaOpaiNatal.pt/reservaTypes reservaTypes.xsd">
    <familia>
        <origem>
            <país>Germany</país>
            <cidade>Porto</cidade>
        </origem>
        <numElementos>2</numElementos>
        <elementos>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Luis</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2002-08-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Francisco</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2002-08-14</dataNascimento>
            </elemento>
        </elementos>
    </familia>
    <preferencias>
        <dataPrevista prioridade="1">2022-12-21</dataPrevista>
        <dataPrevista prioridade="2">2022-12-21</dataPrevista>
        <dataPrevista prioridade="3">2022-12-21</dataPrevista>
    </preferencias>
</reserva>

=== Francisco1915/Processamento-Estruturado-de-Informa-o/xmlxsd/ExemplosReservas/reserva2.xml
<?xml version="1.0" encoding="UTF-8"?>
<reserva xmlns="http://www.visitaOpaiNatal.pt/reservaTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.visitaOpaiNatal.pt/reservaTypes reservaTypes.xsd">
    <familia>
        <origem>
            <país>Russia</país>
            <cidade>Moscow</cidade>
        </origem>
        <numElementos>4</numElementos>
        <elementos>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Tiago</primeiroNome>
                <segundoNome>Moreira</segundoNome>
                <dataNascimento>1999-03-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Mariana</primeiroNome>
                <segundoNome>Silva</segundoNome>
                <dataNascimento>2015-10-25</dataNascimento>
            </elemento>
            <elemento>
                <genero>Masculino</genero>
                <primeiroNome>Rafa</primeiroNome>
                <segundoNome>Sousa</segundoNome>
                <dataNascimento>2015-08-14</dataNascimento>
            </elemento>
            <elemento>
                <genero>Feminino</genero>
                <primeiroNome>Joana</primeiroNome>
                <segundoNome>Moreira</segundoNome>
                <dataNascimento>2008-08-14</dataNascimento>
            </elemento>
        </elementos>
    </familia>
    <preferencias>
        <dataPrevista prioridade="1">2022-11-21</dataPrevista>
        <dataPrevista prioridade="2">2022-12-07</dataPrevista>
        <dataPrevista prioridade="3">2022-12-17</dataPrevista>
    </preferencias>
</reserva>
